### ISSUE TITLE
Design uniforme das telas

### ISSUE THREAD

**Issue by G4BR-13-L** [ICEI-PUC-Minas-PPLES-TI/plf-es-2021-1-ti1-7924100-dificuldades-do-ead#3]
## É necessária coesão e coerência de cores, imagens e bordas de toda a interface da aplicação

**Comment by G4BR-13-L** [comment]
# Cores estipuladas no projeto de interface
```css
:root {
    --tomato-red: #db2727;
    --juice-red: #F59C9C;
    --white: #EBEBEB;
    --grey: #d1d1d1;
    --dark-grey: #333;
    --sun-yellow: #FFBE0B;
    --orange: #FB5607;
    --shok-pink: #FF006E;
    --shallow-purple: #8338EC;
    --blue-sky: #3A86FF;
    --deep-blue: #081732;
    --dark-blue: #000714;
    --spotify-green:#1db954;
}
```
